spring:
    profiles:
        active: prod
    application:
        name: uchat

netty:
  bossThread: 2
  workerThread: 2
  keepalive: true
  backlog: 100

logging:
    config: classpath:log/logback.xml
